INSERT INTO resumes (user_id, title, experience_years, is_published)
VALUES (1, 'Java Developer Middle', 3, true),
       (2, 'C++ Expert', 7, true),
       (3, 'Junior Frontend', 1, true),
       (4, 'Python Senior', 6, true),
       (5, 'Go Backend Junior', 1, true),
       (6, 'iOS Developer', 4, true),
       (7, 'SecOps Lead', 8, true),
       (8, 'Analyst Junior', 1, true),
       (9, 'DevOps Middle', 3, true),
       (10, 'QA Automation', 2, true),
       (11, 'Product Lead', 10, true),
       (12, 'Linux Admin', 5, true),
       (13, 'Ethical Hacker', 4, true),
       (14, 'Project Manager', 3, true),
       (15, 'Cloud Architect', 12, true),
       (16, 'Mobile Team Lead', 7, true),
       (17, 'Designer UI/UX', 2, true),
       (18, 'DBA Oracle/PG', 6, true),
       (19, 'Risk Specialist', 4, true),
       (20, 'BA Analyst', 2, true),
       (1, 'Kotlin Backend', 3, true),
       (2, 'Embedded Developer', 7, true),
       (3, 'JavaScript Dev', 1, true),
       (4, 'Data Scientist', 6, true),
       (5, 'Cloud Engineer', 2, true),
       (6, 'Swift Developer', 4, true),
       (7, 'CISO Expert', 9, true),
       (8, 'Excel Specialist', 1, true),
       (9, 'Site Reliability', 3, true),
       (10, 'Python QA', 2, true),
       (11, 'Product Owner', 8, true),
       (12, 'DevOps Junior', 1, true),
       (13, 'CybSec Junior', 1, true),
       (14, 'Delivery Manager', 5, true),
       (15, 'Solution Architect', 10, true),
       (16, 'Android Dev Senior', 6, true),
       (17, 'Graphic Designer', 3, true),
       (18, 'SQL Developer', 4, true),
       (19, 'Finance Analyst', 5, true),
       (20, 'System Analyst', 3, true);

INSERT INTO skills (resume_id, name)
VALUES (1, 'Java'),
       (1, 'Spring Boot'),
       (1, 'PostgreSQL'),
       (21, 'Kotlin'),
       (21, 'Coroutines'),
       (2, 'C++'),
       (2, 'STL'),
       (2, 'Multithreading'),
       (22, 'Embedded C'),
       (22, 'RTOS'),
       (3, 'React'),
       (3, 'TypeScript'),
       (3, 'CSS3'),
       (23, 'JavaScript'),
       (23, 'Vue.js'),
       (4, 'Python'),
       (4, 'Django'),
       (4, 'Docker'),
       (24, 'Pandas'),
       (24, 'Scikit-learn'),
       (5, 'Golang'),
       (5, 'gRPC'),
       (25, 'Kubernetes'),
       (25, 'AWS'),
       (6, 'Swift'),
       (6, 'SwiftUI'),
       (26, 'Combine'),
       (36, 'Kotlin'),
       (36, 'Android SDK'),
       (7, 'Network Security'),
       (7, 'SIEM'),
       (27, 'CISM'),
       (33, 'Penetration Testing'),
       (8, 'SQL'),
       (8, 'Tableau'),
       (20, 'BPMN'),
       (20, 'UML'),
       (40, 'System Analysis'),
       (9, 'Terraform'),
       (9, 'Ansible'),
       (29, 'Prometheus'),
       (32, 'CI/CD'),
       (10, 'Selenium'),
       (10, 'JUnit'),
       (30, 'PyTest'),
       (29, 'API Testing'),
       (11, 'Agile'),
       (11, 'Scrum'),
       (31, 'Product Roadmap'),
       (14, 'Jira'),
       (17, 'Figma'),
       (17, 'Adobe XD'),
       (37, 'Prototyping');

INSERT INTO education (resume_id, institution, degree, field_of_study, start_year, end_year)
VALUES (1, 'МГТУ им. Н.Э. Баумана', 'Бакалавр', 'Информатика и системы управления', 2016, 2020),
       (2, 'МФТИ', 'Магистр', 'Прикладная математика и физика', 2012, 2018),
       (3, 'НИУ ВШЭ', 'Бакалавр', 'Программная инженерия', 2019, 2023),
       (4, 'МГУ им. М.В. Ломоносова', 'Магистр', 'Вычислительная математика и кибернетика', 2014, 2020),
       (5, 'УрФУ', 'Бакалавр', 'Информационные технологии', 2018, 2022),
       (6, 'СПбГУ', 'Бакалавр', 'Математическое обеспечение администрирование ИС', 2015, 2019),
       (7, 'Академия ФСБ РФ', 'Специалист', 'Информационная безопасность', 2010, 2015),
       (8, 'РЭУ им. Г.В. Плеханова', 'Бакалавр', 'Бизнес-информатика', 2019, 2023),
       (9, 'ИТМО', 'Магистр', 'Облачные технологии', 2016, 2022),
       (10, 'МАИ', 'Бакалавр', 'Автоматизированные системы', 2017, 2021),
       (11, 'МГИМО', 'Магистр', 'Менеджмент в ИТ', 2008, 2014),
       (12, 'СибГУТИ', 'Бакалавр', 'Инфокоммуникационные технологии', 2014, 2018),
       (13, 'МИФИ', 'Магистр', 'Кибербезопасность', 2015, 2021),
       (14, 'РАНХиГС', 'Бакалавр', 'Управление проектами', 2016, 2020),
       (15, 'Иннополис', 'Магистр', 'Software Engineering', 2010, 2016),
       (16, 'ТГУ', 'Бакалавр', 'Разработка мобильных приложений', 2013, 2017),
       (17, 'Британская высшая школа дизайна', 'Диплом', 'Графический дизайн', 2018, 2021),
       (18, 'НГУ', 'Бакалавр', 'Базы данных', 2012, 2016),
       (19, 'Финансовый университет', 'Магистр', 'Анализ рисков', 2015, 2021),
       (20, 'МИЭТ', 'Бакалавр', 'Системный анализ', 2017, 2021),
       (21, 'МГТУ им. Н.Э. Баумана', 'Магистр', 'Computer Science', 2020, 2022),
       (22, 'МФТИ', 'Аспирантура', 'Робототехника', 2018, 2021),
       (23, 'НИУ ВШЭ', 'Курсы', 'Fullstack Developer', 2023, 2023),
       (24, 'МГУ им. М.В. Ломоносова', 'Курсы', 'Data Science Specialization', 2021, 2021),
       (25, 'УрФУ', 'Магистр', 'Cloud Computing', 2022, 2024),
       (26, 'СПбГУ', 'Курсы', 'iOS Advanced', 2020, 2020),
       (27, 'SANS Institute', 'Сертификат', 'CISO Training', 2021, 2022),
       (28, 'Coursera', 'Сертификат', 'Advanced Excel', 2023, 2023),
       (29, 'ИТМО', 'Бакалавр', 'Системное программирование', 2012, 2016),
       (30, 'GeekBrains', 'Диплом', 'QA Automation Engineer', 2021, 2022),
       (31, 'Школа управления Сколково', 'MBA', 'Digital Transformation', 2020, 2022),
       (32, 'Udemy', 'Сертификат', 'Kubernetes Hands-on', 2022, 2022),
       (33, 'Netology', 'Диплом', 'Cybersecurity', 2021, 2022),
       (34, 'ProductSense', 'Сертификат', 'Product Management', 2022, 2022),
       (35, 'Иннополис', 'Бакалавр', 'Computer Science', 2006, 2010),
       (36, 'ТГУ', 'Магистр', 'Mobile Systems', 2017, 2019),
       (37, 'Skillbox', 'Диплом', 'UX Design', 2021, 2022),
       (38, 'OTUS', 'Сертификат', 'PostgreSQL DBA', 2022, 2022),
       (39, 'РЭУ им. Г.В. Плеханова', 'Магистр', 'Экономика', 2016, 2018),
       (40, 'МИЭТ', 'Магистр', 'ИТ-Консалтинг', 2021, 2023);